#!/usr/bin/env node

var fs = require("fs");
var ipfsAPI = require("ipfs-api");

var argv = process.argv.slice(2);

if (argv[0] === "id") {

    var ipfs = ipfsAPI('/ip4/127.0.0.1/tcp/5001');

    ipfs.id(function(err, result) {

        if (err) {
            console.error("IPFS error: %j", err);
            process.exit(1);
        } else {
            console.log("IPFS ID: %j", result.id);
            process.exit(0);    
        }

    });

} else if (argv[0] === "version") {

    var ipfs = ipfsAPI('/ip4/127.0.0.1/tcp/5001');

    ipfs.version(function(err, result) {
        if (err) {
            console.error("IPFS error: %j", err);
            process.exit(1);
        } else {
            console.log("IPFS Version: %j", result);
            process.exit(0);    
        }
    });

} else if (argv[0] === "add") {

    if (argv.length < 2) {
        console.log("Usage: ipfsplay add <file>");
        process.exit(0);
    } else {
        fs.readFile(argv[1], function(err, data) {

            if (err) {
                console.error("FS Error: %j", err);
            } else {

                var ipfs = ipfsAPI('/ip4/127.0.0.1/tcp/5001');

                ipfs.add(data, function(err, result) {
                    if (err) {
                        console.error("IPFS error: %j", err);
                        process.exit(1);
                    } else {
                        console.log("IPFS Object ID: %j", result[0].hash);
                        process.exit(0);    
                    }
                });
            }
            
        });
    }

} else {

    console.log("Usage: ipfsplay <cmd>");
    process.exit(0);

}
